version: "3"
services:
  node:
    image: node:latest
    user: "node"
    working_dir: /home/node/lab1
    environment: 
      - NODE_ENV=development
    volumes:
      - ./:/home/node/lab1
    expose:
      - "8081"
    ports:
      - 3000:3000
      - 3001:3001
    command: "npm run dev"
