version: "3"
services:
  node:
    image: node:latest
    user: "node"
    working_dir: /home/node/lab1
    volumes:
      - ./:/home/node/lab1
    ports:
      - 3000:3000
      - 3001:3001
    command: "npm run dev"
