version: "3"
services: 
  lab1_json_server:
    image: node:latest
    user: "node"
    working_dir: /home/node/lab1
    volumes:
      - ./:/home/node/lab1
    expose: 
      - "8082"
    ports: 
      - "8082:8082"
    command: "npm run dev"