version: "3"
services:
  nginx:
    container_name: nginx_load_balancer
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - json-data-server
      - lite-server

  json-data-server:
    # container_name: json_data_server
    image: vegura/json-server
    volumes: 
      - ./json-server/db.json:/home/lab1/db.json
    expose:
      - "8000"

  lite-server:
    # container_name: lite_server
    image: vegura/lite-server
    volumes:
      - ./lite-server/index.html:/home/lab1/index.html
      - ./lite-server/bs-config.json:/home/lab1/bs-config.json
    expose:
      - "3000"
    
